export class AppConstantsLabel {
  public static movieDetail = {
    MOVIE_NAME: 'MOVIE NAME',
    YEAR: 'YEAR',
    RATINGS: 'RATINGS',
    GENERES:'GENERES',
    CONTENTRATING:'CONTENTRATING',
    DURATION:'DURATION',
    RELEASEDATE:'RELEASEDATE',
    AVERAGERATING:'AVERAGERATING',
    ORIGINALTITLE:'ORIGINALTITLE',
    STORYLINE:'STORYLINE',
    ACTORS:'ACTORS',
    IMDBRATING:'IMDBRATING',
  };
}